; Listing generated by Microsoft (R) Optimizing Compiler Version 19.15.26732.1 

; Generated by VC++ for Common Language Runtime
.file "C:\Users\sam\AppData\Local\Temp\.NETFramework,Version=v4.0.AssemblyAttributes.cpp"
